repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
        exclude: ^strings/
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer

  # Отсортировывает импорты в проекте
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        exclude: __init__.py
        args: [--profile, black, --filter-files]

  # Обновляет синтаксис Python кода в соответствии с последними версиями
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
        args: [--py313-plus]

  # Форматирует код под PEP8
  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.2
    hooks:
      - id: autopep8
        args: [--max-line-length=120, --in-place]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        exclude: "__init__.py"
        #        args: [ "--ignore=E501,F821,W503", "--max-line-length=120" ]
        args: ["--ignore=E501,W503", "--max-line-length=120"]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.13
        args: [--line-length=120]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff-check
        args: ["--fix", "--line-length=120"]
      - id: ruff-format
        args: ["--line-length=120"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.0
    hooks:
      - id: mypy
        additional_dependencies: ["types-PyYAML"]
